config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :rooms, only: %i[index show] do
    resources :bookings, only: %i[new create]
  end
  get '*unmatched_route', to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :starts_at, presence: true
  validates :ends_at, presence: true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :bookings, through: :rooms, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel

  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :capacity, presence: true
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }
  validates :price_per_night, presence: true
  validates :price_per_night, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @room = Room.find(params[:room_id])
    @booking = Booking.new
  end

  def create
    @room = Room.find(params[:room_id])
    @booking = Booking.new(booking_params)
    @booking.room = @room
    @booking.user = current_user
    redirect_to room_path(@room), notice: "An error has occured, please try again" unless @booking.save
  end

  private

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at, :guests)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @best_rooms = Room.first(3)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @booking = Booking.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <%= simple_form_for [room, booking] do |f| %>
      <%= f.input :starts_at, as: :string, label: "Check-in date", input_html: {id: "range_start", maxlength: 3}, wrapper_html: { class: "inline_field_wrapper" } %>
      <%= f.input :ends_at, as: :string, label: "Check-out date", input_html: {id: "range_end", maxlength: 3}, wrapper_html: { class: "inline_field_wrapper" } %>
      <%= f.input :guests, as: :select, collection: (1..@room.capacity), label: "Number of guests" %>
      <%= f.button :submit, "Book", class: "btn btn-red", id: "sweet-alert-demo" %>
      <%= link_to "", room_path(@room), method: :get, id: "post-link", class: "hidden" %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Huone</title>
    <%= favicon_link_tag "favicon/favicon.png" %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <% if params[:controller] == "pages" && params[:action] == "home" %>
      <%= render 'shared/banner' %>
    <% end %>

    <div class="container mt-4 mb-4">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h2>Popular rooms</h2>

<div class="cards-rooms-container">
  <% @best_rooms.each do |room| %>
    <%= render 'rooms/card_room', room: room %>
  <% end %>
</div>

app/views/rooms/_card_room.html.erb
<div class="card-trip">
  <div class="card-trip-image">
    <%= link_to room_path(room) do %>
    <%= cl_image_tag room.photo.key, crop: :fill, class: "card-trip-img"%>
    <% end %>
  </div>
  <div class="card-trip-infos">
    <div>
      <h2><%= link_to room.hotel.name, room_path(room) %></h2>
      <p><%= room.hotel.address %></p>
      <p><i class="fa-solid fa-user-group"></i> <%= room.capacity %></p>
    </div>
    <h2 class="card-trip-pricing"><%= room.price_per_night%> €/night</h2>
  </div>
</div>

app/views/rooms/index.html.erb
<h2>All rooms</h2>

<div class="cards-rooms-container">
  <% @rooms.each do |room| %>
    <%= render 'rooms/card_room', room: room %>
  <% end %>
</div>
<br>
<br>
<br>

app/views/rooms/show.html.erb
<div class="room-container">
  <div class="room-image">
    <%= link_to rooms_path do %>
      <i class="fa-solid fa-arrow-left"></i> Go to rooms list
    <% end %>
    <%= cl_image_tag @room.photo.key, crop: :fill, class: "room-img"%>
  </div>

  <div class="room-infos">
    <h3><%= @room.hotel.name %></h2>
    <p>Price: <%= @room.price_per_night %>€ per night</p>
    <p><i class="fa-solid fa-user-group"></i> <%= @room.capacity %></p>
    <hr>
    <h3>Hotel's address</h2>
    <p><%= @room.hotel.address %></p>
    <%= render "bookings/form", room: @room, booking: @booking %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=asset_path("banner.jpg")%>);">
  <div class="container">
    <h1>A good huone for a good night sleep</h1>
    <%= link_to "See all rooms", rooms_path, class: "btn-red" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-pinterest"></i></a>
    <a href="#"><i class="fab fa-tiktok"></i></a>
  </div>
  <div class="footer-copyright">
    Huone simply means bedroom in Finnish. Wishing you a <i class="fas fa-heart"></i> night in your next Huone.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar2.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link btn-red" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>